// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_Jeu_Role.Data;

#nullable disable

namespace Projet_Jeu_Role.Migrations
{
    [DbContext(typeof(ProjetMVCContext))]
    partial class ProjetMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Projet_Jeu_Role.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnswerContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituationEnterId")
                        .HasColumnType("int");

                    b.Property<int?>("SituationExitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SituationEnterId");

                    b.HasIndex("SituationExitId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerContent = "Aller à la boulangerie",
                            SituationEnterId = 1,
                            SituationExitId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerContent = "Aller à la mairie",
                            SituationEnterId = 1,
                            SituationExitId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerContent = "Aller au quartier résidentiel",
                            SituationEnterId = 1,
                            SituationExitId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerContent = "Aller à la maison manger gateau magique",
                            SituationEnterId = 1,
                            SituationExitId = 1
                        },
                        new
                        {
                            Id = 5,
                            AnswerContent = "Demander un gateau magique",
                            SituationEnterId = 2,
                            SituationExitId = 3
                        },
                        new
                        {
                            Id = 6,
                            AnswerContent = "Aller à la place du village",
                            SituationEnterId = 2,
                            SituationExitId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerContent = "Ne rien faire",
                            SituationEnterId = 2,
                            SituationExitId = 2
                        },
                        new
                        {
                            Id = 8,
                            AnswerContent = "Aller à la place du village",
                            SituationEnterId = 2,
                            SituationExitId = 2
                        });
                });

            modelBuilder.Entity("Projet_Jeu_Role.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Projet_Jeu_Role.Models.Situation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SituationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Situations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SituationDescription = "Place du village",
                            SituationName = "Place du village"
                        },
                        new
                        {
                            Id = 2,
                            SituationDescription = "Boulangerie",
                            SituationName = "Boulangerie"
                        },
                        new
                        {
                            Id = 3,
                            SituationDescription = "Mairie",
                            SituationName = "Mairie"
                        },
                        new
                        {
                            Id = 4,
                            SituationDescription = "Maison Johnny",
                            SituationName = "Maison Johnny"
                        },
                        new
                        {
                            Id = 5,
                            SituationDescription = "Maison",
                            SituationName = "Maison"
                        });
                });

            modelBuilder.Entity("Projet_Jeu_Role.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Projet_Jeu_Role.Models.Answer", b =>
                {
                    b.HasOne("Projet_Jeu_Role.Models.Situation", "SituationEnter")
                        .WithMany("AnswerEnter")
                        .HasForeignKey("SituationEnterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet_Jeu_Role.Models.Situation", "SituationExit")
                        .WithMany("AnswerExit")
                        .HasForeignKey("SituationExitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SituationEnter");

                    b.Navigation("SituationExit");
                });

            modelBuilder.Entity("Projet_Jeu_Role.Models.Situation", b =>
                {
                    b.Navigation("AnswerEnter");

                    b.Navigation("AnswerExit");
                });
#pragma warning restore 612, 618
        }
    }
}
